### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [jkfids/qiskit-entangle#1]
I recently came across your project qiskit-entangle and I noticed that the repository github.com/jkfids/qiskit-entangle currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by jkfids** [comment]
Hi Juan. Thank you for your comment. This repository contains code related to the work in [Characterization of entanglement on superconducting quantum computers of up to 414 qubits](https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.6.033155). This repository was meant to be private, and I was intending to eventually rewrite a portion of this repository into an installable package (name not final), but I've now left it public and added an Apache 2.0 license.
